modify sanitytests/fpga, can sythesize successfully in vivado
chipsalliance/playground pull request #35
Opened 2022-08-16 05:59 UTC by JACKLIAO0

modified file sanitytests/fpga/src/DesignKeyWrapper.scala and sanitytests/fpga/src/FpgaHarness.scala, to make sythesize with 50MHz(max 80MHz) clock frequency in vivado can work correctly.

2022-08-22 06:26 UTC, sequencer requested changes

2022-08-25 05:43 UTC, sequencer commented
please split arty100t from fpga

2022-08-25 05:45 UTC, JACKLIAO0 commented
I have added a case in Top config to modify the FPGAFrequencyKey.

2022-08-25 05:46 UTC, JACKLIAO0 commented
> please split arty100t from fpga

add a new branch named arty100T in playground?

2022-08-25 06:08 UTC, sequencer commented
Provide both arty and vcu at the same time

2022-08-26 07:57 UTC, sequencer requested changes

2022-08-26 07:57 UTC, sequencer commented on sanitytests/fpga/src/FPGATest.scala
> -//      val configs = Seq(classOf[FPGATestConfig], classOf[freechips.rocketchip.system.DefaultConfig])
Change FPGATest to VCU118Test and Arty100TTest

2022-09-21 12:50 UTC, JACKLIAO0 commented
@sequencer there is an error that i have no idea how to reslove, please have a see

2023-02-22 03:44 UTC, closed without merging